[package]
name = "rust-tag-matcher"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module"] }
aho-corasick = "1.0"
globset = "0.4"
regex = "1.10"

[lib]
name = "rust_tag_matcher"
crate-type = ["cdylib"]
path = "src/lib.rs"
