name: "VogonPoetry"
description: "The least pleasant pipeline experience in the galaxy"
pipeline:
  - id: classify
    type: classify_request
    config:
      model: "gpt-4"
    output_key: tags

  - id: retrieve_mem
    type: retrieve_memory
    requires: ["classify"]
    config:
      top_k: 5
      tag_key: "tags"
    output_key: memories

  - id: select_tools
    type: select_tools
    requires: ["classify"]
    config:
      filter_tags_from: "tags"
    output_key: tools

  - id: prompt_build
    type: prompt_builder
    requires: ["retrieve_mem", "select_tools"]
    config:
      template: "rag_template"
      input_keys:
        memory: "memories"
        tools: "tools"
        user_input: "input"
    output_key: prompt

  - id: send
    type: send_to_llm
    requires: ["prompt_build"]
    config:
      provider: "openrouter"
      model: "mistral:7b-instruct"
      input_key: "prompt"
    output_key: final_response
