[package]
name = "rust-embedder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "rust_embedder"
path = "src/lib.rs"

[[bin]]
name = "rust-embedder"
path = "src/main.rs"